import { argv } from "node:process";
import fs from "fs"

// -------------- constants --------------

const ROOTDIR = argv[2];
const OUTFILE = argv[3];

// -------------- functions --------------

function readDir(dirname: string): string[]
{
	let entries: string[] = [];
	const items = fs.readdirSync(dirname, { withFileTypes: true });

	for (const item of items)
	{
		if (item.isFile())
			entries.push(dirname.replace(ROOTDIR, '.') + '/' + item.name);
		else if (item.isDirectory())
			entries = entries.concat(readDir(dirname + '/' + item.name));
	}

	return entries;
}

function writeFile(filename: string, entries: string[])
{
	const content = JSON.stringify(entries, null, '\t');
	try
	{
		fs.writeFileSync(filename, content);
	}
	catch (err)
	{
		console.error(err);
		process.exit(1);
	}
}

// -------------- main --------------

function main()
{
	if (ROOTDIR === "-h" || ROOTDIR === "--help")
	{
		console.log("Script used to export the list of files generated by NextJS build, in order to cache them with the service worker.\n");
		console.log("Usage: node list_out_dir.ts <INPUT DIR> <OUTPUT FILE>\n");
		console.log("\t<INPUT DIR>: path to the directory to list the files, generally the output of NextJS ('out/').");
		console.log("\t<OUTPUT FILE>: path to the JSON file that needs to be generated.\n");
		console.log("Example:");
		console.log("node list_out_dir.ts out/ out/files_to_cache.json\n");
		process.exit(0);
	}
	if (!ROOTDIR || !fs.existsSync(ROOTDIR) || !fs.statSync(ROOTDIR).isDirectory())
	{
		console.error(`Bad input folder given: "${ROOTDIR}"`);
		process.exit(1);
	}
	if (!OUTFILE)
	{
		console.error("missing argument <OUTPUT FILE>. See help (rerun with '--help' argument)");
		process.exit(1);
	}

	console.log(`processing directory ${ROOTDIR}...`);

	const entries = ["."].concat(readDir(ROOTDIR));
	console.log(`Found ${entries.length} entries. Writing to ${OUTFILE}...`);
	writeFile(OUTFILE, entries);
	console.log("process finished.");
}

main();
